// flow-typed signature: 99888a4ad14861e21bcbc0fea6c90d01
// flow-typed version: <<STUB>>/@testing-library/dom_v7.24.5/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/dom/dist/@testing-library/dom.cjs' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/@testing-library/dom.esm' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/@testing-library/dom.umd' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/@testing-library/dom.umd.min' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/config' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/event-map' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/events' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/get-node-text' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/get-queries-for-element' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/get-user-code-frame' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/helpers' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/matches' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/pretty-dom' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/all-utils' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/alt-text' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/display-value' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/label-text' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/placeholder-text' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/role' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/test-id' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/text' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/queries/title' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/query-helpers' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/role-helpers' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/screen' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/suggestions' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/wait-for-dom-change' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/wait-for-element-to-be-removed' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/wait-for-element' {
  declare module.exports: any;
}

declare module '@testing-library/dom/dist/wait-for' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/dom/dist/@testing-library/dom.cjs.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/@testing-library/dom.cjs'>;
}
declare module '@testing-library/dom/dist/@testing-library/dom.esm.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/@testing-library/dom.esm'>;
}
declare module '@testing-library/dom/dist/@testing-library/dom.umd.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/@testing-library/dom.umd'>;
}
declare module '@testing-library/dom/dist/@testing-library/dom.umd.min.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/@testing-library/dom.umd.min'>;
}
declare module '@testing-library/dom/dist/config.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/config'>;
}
declare module '@testing-library/dom/dist/event-map.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/event-map'>;
}
declare module '@testing-library/dom/dist/events.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/events'>;
}
declare module '@testing-library/dom/dist/get-node-text.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/get-node-text'>;
}
declare module '@testing-library/dom/dist/get-queries-for-element.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/get-queries-for-element'>;
}
declare module '@testing-library/dom/dist/get-user-code-frame.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/get-user-code-frame'>;
}
declare module '@testing-library/dom/dist/helpers.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/helpers'>;
}
declare module '@testing-library/dom/dist/index' {
  declare module.exports: $Exports<'@testing-library/dom/dist'>;
}
declare module '@testing-library/dom/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist'>;
}
declare module '@testing-library/dom/dist/matches.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/matches'>;
}
declare module '@testing-library/dom/dist/pretty-dom.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/pretty-dom'>;
}
declare module '@testing-library/dom/dist/queries/all-utils.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/all-utils'>;
}
declare module '@testing-library/dom/dist/queries/alt-text.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/alt-text'>;
}
declare module '@testing-library/dom/dist/queries/display-value.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/display-value'>;
}
declare module '@testing-library/dom/dist/queries/index' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries'>;
}
declare module '@testing-library/dom/dist/queries/index.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries'>;
}
declare module '@testing-library/dom/dist/queries/label-text.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/label-text'>;
}
declare module '@testing-library/dom/dist/queries/placeholder-text.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/placeholder-text'>;
}
declare module '@testing-library/dom/dist/queries/role.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/role'>;
}
declare module '@testing-library/dom/dist/queries/test-id.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/test-id'>;
}
declare module '@testing-library/dom/dist/queries/text.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/text'>;
}
declare module '@testing-library/dom/dist/queries/title.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/queries/title'>;
}
declare module '@testing-library/dom/dist/query-helpers.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/query-helpers'>;
}
declare module '@testing-library/dom/dist/role-helpers.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/role-helpers'>;
}
declare module '@testing-library/dom/dist/screen.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/screen'>;
}
declare module '@testing-library/dom/dist/suggestions.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/suggestions'>;
}
declare module '@testing-library/dom/dist/wait-for-dom-change.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/wait-for-dom-change'>;
}
declare module '@testing-library/dom/dist/wait-for-element-to-be-removed.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/wait-for-element-to-be-removed'>;
}
declare module '@testing-library/dom/dist/wait-for-element.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/wait-for-element'>;
}
declare module '@testing-library/dom/dist/wait-for.js' {
  declare module.exports: $Exports<'@testing-library/dom/dist/wait-for'>;
}
